#ifndef ERRNO_HPP
#define ERRNO_HPP

enum ERRNO { SUCCESS,
	     UNDEFINED,
	     INVALID_ARGUMENT,
	     INVALID_VALUE,
	     NULL_POINTER_DEREFENCE,
	     ILLEGAL_MEMORY_ACCESS,
	     NUMERIC_OVERFLOW,
	     NUMERIC_UNDERFLOW,
	     PARTIAL_READ,
	     INVALID_READ,
	     NAN_GIVEN_FOR_SORTING };

#endif // ERRNO_HPP
